kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: res-1-1-bind
  namespace: res-1-1
subjects:
- kind: ServiceAccount
  name: res-1-1-reader
  namespace: res-1-1
roleRef:
  kind: ClusterRole
  name: tfcluster
  apiGroup: rbac.authorization.k8s.io