apiVersion: kubeflow.org/v1
kind: TFJob
metadata: {name: vgg-2-2, namespace: vgg-2-2}
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          serviceAccount: vgg-2-2-reader
          hostPID: true
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: cpusch
                        operator: In
                        values: ['true']
                  weight: 10
                - preference:
                    matchExpressions:
                      - key: cpukpro
                        operator: In
                        values: ['0', '1']
                  weight: 5
                - preference:
                    matchExpressions:
                      - key: wokpro
                        operator: In
                        values: ['2']
                  weight: 2
          containers:
          - args: [--training_step=20000, --batch_size=8, --interval=0.3, --task_id=2,
                     --rtimes=2, --tag=ms, --retry=0, --dbhost=172.16.190.97, --update_min_step=22000,
                     --step_update=200, --update_start=1.25, --update_end=1.75, --update_delay=2.0,
                     --channel1=32, --channel2=64, --channel3=128, --channel4=256, --channel5=512,
                     --num_layer1=2, --num_layer2=3, --num_layer3=1, --num_layer4=2, --num_layer5=2,
                     --num_layers=21,--num_gpus=1]

            image: 172.16.190.90:5000/vgg-ps:1.15
            name: tensorflow
            volumeMounts:
            - {mountPath: /tmp/train, name: vgg-2-2, readOnly: false}
            - {mountPath: /tfdata/imagenet_data, name: vgg-2-2-data, readOnly: false}
          volumes:
          - hostPath: {path: /data/tfdata/k8snfs/vgg-2-2}
            name: vgg-2-2
          - hostPath: {path: /data/tfdata/imagenet_data}
            name: vgg-2-2-data
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          serviceAccount: vgg-2-2-reader
          hostPID: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: gpu
                        operator: In
                        values: ['true']
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: gpusch
                        operator: In
                        values: ['true']
                  weight: 12
                - preference:
                    matchExpressions:
                      - key: gpupro
                        operator: In
                        values: ['0','1']
                  weight: 6
                - preference:
                    matchExpressions:
                      - key: gpupro
                        operator: In
                        values: ['2']
                  weight: 3
          containers:
          - args: [--training_step=20000, --batch_size=8, --interval=0.3, --task_id=2,
                     --rtimes=2, --tag=ms, --retry=0, --dbhost=172.16.190.97, --update_min_step=22000,
                     --step_update=200, --update_start=1.25, --update_end=1.75, --update_delay=2.0,
                     --channel1=32, --channel2=64, --channel3=128, --channel4=256, --channel5=512,
                     --num_layer1=2, --num_layer2=3, --num_layer3=1, --num_layer4=2, --num_layer5=2,
                     --num_layers=21,--num_gpus=1]

            image: 172.16.190.90:5000/vgg-worker:1.15
            name: tensorflow
            resources:
              limits:
                nvidia.com/gpu: 1
              requests:
                nvidia.com/gpu: 1
            volumeMounts:
            - {mountPath: /tmp/train, name: vgg-2-2, readOnly: false}
            - {mountPath: /tfdata/imagenet_data, name: vgg-2-2-data, readOnly: false}
          volumes:
          - hostPath: {path: /data/tfdata/k8snfs/vgg-2-2}
            name: vgg-2-2
          - hostPath: {path: /data/tfdata/imagenet_data}
            name: vgg-2-2-data

