import yaml
template = \
{'apiVersion': 'kubeflow.org/v1',
 'kind': 'TFJob',
 'metadata': {'name': 'vgg1', 'namespace': 'vgg1'},
 'spec':
     {'tfReplicaSpecs':
          {'PS':
               {'replicas': 2,
                'restartPolicy': 'Never',
                'template':
                    {'spec':
                         {'containers':
                              [{'name': 'tensorflow',
                                'image': 'qinhua/vgg:1.0',
                                'args': ['--train_steps=100'],
                                'volumeMounts':
                                    [{'name': 'vgg1',
                                      'mountPath': '/tmp/train',
                                      'readOnly': False}]}],
                          'volumes': [{'name': 'vgg1',
                                       'hostPath': {'path': '/tfdata/k8snfs/vgg1'}}
                                      ]
                          }
                     }
                },
           'Worker': {'replicas': 4,
                      'restartPolicy': 'Never',
                      'template':
                          {'spec':
                               {'containers':
                                    [
                                        {'name': 'tensorflow',
                                         'image': 'qinhua/vgg:1.0',
                                         'args': ['--train_steps=100'],
                                         'volumeMounts':
                                             [{'name': 'vgg1', 'mountPath': '/tmp/train', 'readOnly': False}]
                                         }
                                    ],
                                'volumes': [{'name': 'vgg1', 'hostPath': {'path': '/tfdata/k8snfs/vgg1'}}]
                               }
                          }
                      }
           }
      }
 }

vgg_file = open('tf_job_vgg.yaml','r')

vgg_template = yaml.load(vgg_file.read())
print(vgg_template)
res_file = open('tf_job_res.yaml','r')
res_template = yaml.load(res_file.read())
print(res_template)
res2_file = open('tf_job_res2.yaml','r')
res2_template = yaml.load(res2_file.read())
print(res2_template)
xception_file = open('tf_job_xception.yaml','r')
xception_template = yaml.load(xception_file.read())
print(xception_template)
den_file = open('tf_job_den.yaml','r')
den_template = yaml.load(den_file.read())
print(den_template)
ns_file = open('namespace_temp.yaml','r')
ns_template = yaml.load(ns_file.read())
print(ns_template)
print(vgg_template['spec']['tfReplicaSpecs']['PS']['template']['spec']['volumes'][0]['hostPath']['path'])


class TaskTemplate():
   # VGG = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'vgg5', 'namespace': 'vgg5'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/vggdb:1.5', 'args': ['--training_step=100', '--channel1=64', '--channel2=128', '--channel3=256', '--channel4=512', '--channel5=512', '--num_layer1=2', '--num_layer2=2', '--num_layer3=4', '--num_layer4=4', '--num_layer5=4', '--num_layers=19', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'vgg5', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'vgg5', 'hostPath': {'path': '/tfdata/k8snfs/vgg5'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0']}]}}, {'weight': 3, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/vggdb:1.5', 'args': ['--training_step=100', '--channel1=64', '--channel2=128', '--channel3=256', '--channel4=512', '--channel5=512', '--num_layer1=2', '--num_layer2=2', '--num_layer3=4', '--num_layer4=4', '--num_layer5=4', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'vgg5', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'vgg5', 'hostPath': {'path': '/tfdata/k8snfs/vgg5'}}]}}}}}}
    VGG = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'vgg5', 'namespace': 'vgg5'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0', '1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/vggdb:1.5', 'args': ['--training_step=100', '--channel1=64', '--channel2=128', '--channel3=256', '--channel4=512', '--channel5=512', '--num_layer1=2', '--num_layer2=2', '--num_layer3=4', '--num_layer4=4', '--num_layer5=4', '--num_layers=19', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'vgg5', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'vgg5', 'hostPath': {'path': '/tfdata/k8snfs/vgg5'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0','1']}]}},{'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/vggdb:1.5', 'args': ['--training_step=100', '--channel1=64', '--channel2=128', '--channel3=256', '--channel4=512', '--channel5=512', '--num_layer1=2', '--num_layer2=2', '--num_layer3=4', '--num_layer4=4', '--num_layer5=4', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'vgg5', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'vgg5', 'hostPath': {'path': '/tfdata/k8snfs/vgg5'}}]}}}}}}
   # RES = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'res3', 'namespace': 'res3'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/resdb:1.6', 'args': ['--rtimes=3', '--training_step=100', '--bottle=1', '--layer1=3', '--layer2=4', '--layer3=8', '--layer4=3', '--channel1=32', '--channel2=48', '--channel3=128', '--channel4=256', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'res3', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'res3', 'hostPath': {'path': '/tfdata/k8snfs/res3'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0']}]}}, {'weight': 3, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/resdb:1.6', 'args': ['--rtimes=3', '--training_step=100', '--bottle=1', '--layer1=3', '--layer2=4', '--layer3=8', '--layer4=3', '--channel1=32', '--channel2=48', '--channel3=128', '--channel4=256', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'res3', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'res3', 'hostPath': {'path': '/tfdata/k8snfs/res3'}}]}}}}}}
    RES = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'res3', 'namespace': 'res3'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0', '1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/resdb:1.6', 'args': ['--rtimes=3', '--training_step=100', '--bottle=1', '--layer1=3', '--layer2=4', '--layer3=8', '--layer4=3', '--channel1=32', '--channel2=48', '--channel3=128', '--channel4=256', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'res3', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'res3', 'hostPath': {'path': '/tfdata/k8snfs/res3'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0','1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/resdb:1.6', 'args': ['--rtimes=3', '--training_step=100', '--bottle=1', '--layer1=3', '--layer2=4', '--layer3=8', '--layer4=3', '--channel1=32', '--channel2=48', '--channel3=128', '--channel4=256', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'res3', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'res3', 'hostPath': {'path': '/tfdata/k8snfs/res3'}}]}}}}}}
    RE = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 're1', 'namespace': 're1'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0', '1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/res2db:1.1', 'args': ['--training_step=100', '--stack=10', '--channel1=16', '--channel2=32', '--channel3=64', '--channel4=128', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 're1', 'mountPath': '/tmp/train'}]}], 'volumes': [{'name': 're1', 'hostPath': {'path': '/tfdata/k8snfs/re1'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0','1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/res2db:1.1', 'args': ['--training_step=100', '--stack=10', '--channel1=16', '--channel2=32', '--channel3=64', '--channel4=128', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 're1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 're1', 'hostPath': {'path': '/tfdata/k8snfs/re1'}}]}}}}}}
    XCEPTION = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'xception1', 'namespace': 'xception1'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0', '1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/xceptiondb:1.1', 'args': ['--training_step=100', '--repeat=8', '--channel1=32', '--channel2=64', '--channel3=128', '--channel4=256', '--channel5=728', '--channel6=1024', '--channel7=1536', '--channel8=2048', '--interval=0.5', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'xception1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'xception1', 'hostPath': {'path': '/tfdata/k8snfs/xception1'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0','1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/xceptiondb:1.1', 'args': ['--training_step=100', '--repeat=8', '--channel1=32', '--channel2=64', '--channel3=128', '--channel4=256', '--channel5=728', '--channel6=1024', '--channel7=1536', '--channel8=2048', '--interval=0.5', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'xception1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'xception1', 'hostPath': {'path': '/tfdata/k8snfs/xception1'}}]}}}}}}
   # RE = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 're1', 'namespace': 're1'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/res2db:1.1', 'args': ['--training_step=100', '--stack=10', '--channel1=16', '--channel2=32', '--channel3=64', '--channel4=128', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 're1', 'mountPath': '/tmp/train'}]}], 'volumes': [{'name': 're1', 'hostPath': {'path': '/tfdata/k8snfs/re1'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0']}]}}, {'weight': 3, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/res2db:1.1', 'args': ['--training_step=100', '--stack=10', '--channel1=16', '--channel2=32', '--channel3=64', '--channel4=128', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 're1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 're1', 'hostPath': {'path': '/tfdata/k8snfs/re1'}}]}}}}}}
   # XCEPTION = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'xception1', 'namespace': 'xception1'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/xceptiondb:1.1', 'args': ['--training_step=100', '--repeat=8', '--channel1=32', '--channel2=64', '--channel3=128', '--channel4=256', '--channel5=728', '--channel6=1024', '--channel7=1536', '--channel8=2048', '--interval=0.5', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'xception1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'xception1', 'hostPath': {'path': '/tfdata/k8snfs/xception1'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0']}]}}, {'weight': 3, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['1']}]}}, {'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/xceptiondb:1.1', 'args': ['--training_step=100', '--repeat=8', '--channel1=32', '--channel2=64', '--channel3=128', '--channel4=256', '--channel5=728', '--channel6=1024', '--channel7=1536', '--channel8=2048', '--interval=0.5', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'xception1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'xception1', 'hostPath': {'path': '/tfdata/k8snfs/xception1'}}]}}}}}}
    DEN = {'apiVersion': 'kubeflow.org/v1', 'kind': 'TFJob', 'metadata': {'name': 'den1', 'namespace': 'den1'}, 'spec': {'tfReplicaSpecs': {'PS': {'replicas': 2, 'restartPolicy': 'Never', 'template': {'spec': {'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/dendb:1.3', 'args': ['--training_step=100', '--L=130', '--k=24', '--BC=1', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'den1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'den1', 'hostPath': {'path': '/tfdata/k8snfs/den1'}}]}}}, 'Worker': {'replicas': 4, 'restartPolicy': 'Never', 'template': {'spec': {'affinity': {'nodeAffinity': {'preferredDuringSchedulingIgnoredDuringExecution': [{'weight': 10, 'preference': {'matchExpressions': [{'key': 'woksch', 'operator': 'In', 'values': ['true']}]}}, {'weight': 5, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['0','1']}]}},{'weight': 2, 'preference': {'matchExpressions': [{'key': 'wokpro', 'operator': 'In', 'values': ['2']}]}}]}}, 'containers': [{'name': 'tensorflow', 'image': '192.168.128.17:5000/dendb:1.3', 'args': ['--training_step=100', '--L=130', '--k=24', '--BC=1', '--interval=1.0', '--task_id=1', '--rtimes=1', "--tag='ms'"], 'volumeMounts': [{'name': 'den1', 'mountPath': '/tmp/train', 'readOnly': False}]}], 'volumes': [{'name': 'den1', 'hostPath': {'path': '/tfdata/k8snfs/den1'}}]}}}}}}
    NS = {'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'res1'}}

